### ISSUE TITLE
Test case 0121

### ISSUE THREAD

**Issue by awwright** [rdfa/rdfa.github.io#19]
In the test suite, the rdfa1.1/XML case <http://rdfa.info/test-suite/test-cases/rdfa1.1/xml/0121.sparql> lists different patterns than <http://rdfa.info/test-suite/test-cases/rdfa1.1/xml/0121.ttl>.

What's the test result supposed to be?

**Comment by gkellogg** [comment]
The reason SPARQL was used, IIRC, is that a processor may produce more triples than what is tested for. All of the turtle files should match the sparql files.

**Comment by awwright** [comment]
Thanks @gkellogg 

When I find the time I'll see if I can write a script to verify the .ttl files against the .sparql files, and send a PR if there's anything else.
