### ISSUE TITLE
Inconsistent JSON-LD context

### ISSUE THREAD

**Issue by rubensworks** [rdfa/rdfa.github.io#24]
The [JSON-LD version of RDFa's initial context](https://www.w3.org/2013/json-ld-context/rdfa11) seems to be inconsistent with respect to the [HTML-version](https://www.w3.org/2011/rdfa-context/rdfa-1.1).

Concretely, I've found the following differences:
* `csvw: http://www.w3.org/ns/csvw#` is missing in the JSON-LD context
* The HTML version uses `http://schema.org/` for `schema:`, while the JSON-LD context uses `https://schema.org/`

I was not sure where to report this issue, the only place I could found an RDFa JSON-LD context was [here](https://github.com/json-ld/json-ld.org/blob/master/contexts/rdfa11.jsonld), but that one seems outdated, so I assume there is another location for this.

**Comment by iherman** [comment]
Oops, my mistake. Made the changes and uploaded the new version.

Thanks @rubensworks!
