### ISSUE TITLE
Tests with mailto are encoded on GitHub Pages

### ISSUE THREAD

**Issue by rubensworks** [rdfa/rdfa.github.io#25]
I'm not exactly sure why, but some of the tests (like [html5/0065](https://github.com/rdfa/rdfa.github.io/blob/541aee19ebb4ded9766d2fd9ff13c174aefb02ad/test-suite/test-cases/rdfa1.1/html5/0065.html) have their `mailto` IRIs encoded by cloudflare, as can be seen here: http://rdfa.info/test-suite/test-cases/rdfa1.1/html5/0065.html.

Obviously, this causes test failures when the test suite is being traversed over GitHub pages, as RDFa does not require JavaScript to run over the DOM before parsing.

Is it possible that there's some configuration active that does this encoding? (Perhaps something [like this](https://davemateer.com/2018/01/08/SSL-on-Github-Pages) is active)

**Comment by gkellogg** [comment]
This needs to be looked into, it should be the same as https://rdfa.github.io/test-suite/test-cases/rdfa1.1/html5/0065.html, but that redirects to the rdfa.info site. Dig reports the IP address for rdfa.info to be 69.172.201.153, which is not associated with GitHub, and there are some [reports](https://exchange.xforce.ibmcloud.com/ip/69.172.201.153), that this is a phishing site.

It could be that the DNS entry was never updated from Digital Bazaar's servers (@davidlehn?), and we're seeing some effects of their firewalls.

IIRC, DNS is owned and managed by Creative Commons.

BTW, the self-running test-suite could use some work. It's mid-port to a JavaScript based implementation that was having problems with some ASK queries. We'll probably need to get this going again if we start dealing with text direction use cases.

**Comment by davidlehn** [comment]
I don't think Digital Bazaar is managing rdfa.info.  Or at least not with the credentials or servers I checked.  The nameservers are set to cloudflare, so it does look like you just need to find whoever controls the domain and get them to turn off that cloudflare email munging.

Perhaps @msporny knows who to talk to?

**Comment by gkellogg** [comment]
I contacted someone years ago, I’ll see if I can dig it up. At this point, we should set it up to use github pages directly, and figure out the test suite runner later. I think we have statically rendered versions of all the tests anyway, which we can list.

**Comment by msporny** [comment]
> Perhaps @msporny knows who to talk to?

Creative Commons still owns the domain... we tried to get them to transfer it to us a while ago, no dice. We could ask again.  :(

**Comment by gkellogg** [comment]
> > Perhaps @msporny knows who to talk to?
> 
> Creative Commons still owns the domain... we tried to get them to transfer it to us a while ago, no dice. We could ask again. :(

That would be great; I’ve gotten no response from the former contact at Creative Commons. I thought we had changed it to GitHub pages before, but it doesn't seem that the IP address is pointing there, and I can't get any useful information about it.

**Comment by gkellogg** [comment]
No response from my old contact. @msporny, do you know someone who can help?

**Comment by rubensworks** [comment]
@gkellogg They actually did reply, but for some reason you were not included in the recipients. Forwarding the e-mail to you now.

**Comment by rubensworks** [comment]
For reference, Cloudflare caching has been disabled, and `mailto` links are not rewritten anymore.

Thanks a lot for the help!
